# @package _global_

task:
  name: batch_integration
  model_name:
    - CancerFoundation
    - scGPT_full
    - scGPT_pancancer
  dataset_name: neftel_ss2
  run_group: ${task.dataset_name}

  # Paths derived from model_name and dataset_name
  data:
    data_root: data/batch_integration/${task.dataset_name}/
    ground_truth: ground_truth/${task.dataset_name}

  # Column names in the Ground Truth .obs dataframe
  metadata:
    batch_key: sample
    label_key: subtype

  # Configuration for scib-metrics
  metrics:
    embedding_key: X_emb  # Where to store user embeddings in the merged object
    n_neighbors: 15         # For kNN graph construction

  # dataset:
  #   name: Neftel_brain_10X
  #   n_hvg: null  # Number of highly variable genes to select

  parameters:
    seed: 42
    n_replicates: 3
