# @package _global_

task:
  name: gene_perturbation

  paths:
    ground_truth: data/gene_perturbation/norman19/norman19_processed.h5ad
    submission: data/gene_perturbation/norman19/submission.h5ad
