defaults:
  - task: ???  # 1. Load configs/task/batch_integration.yaml
  - _self_                   # 2. Then apply any overrides from this file (if any)

# You can still define global variables here if you want
seed: 42
